-- update-gallery.sql
-- Met à jour le gallery JSON de chaque projet avec les chemins standardisés
-- À exécuter dans Supabase SQL Editor

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/avenir-telecom-lightning-app/cover.webp"},{"alt":"Screenshot 1","src":"/projects/avenir-telecom-lightning-app/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/avenir-telecom-lightning-app/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/avenir-telecom-lightning-app/screenshot-3.webp"}]'::jsonb WHERE slug = 'avenir-telecom-lightning-app';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/digit-learning-salesforce-update/cover.webp"},{"alt":"Screenshot 1","src":"/projects/digit-learning-salesforce-update/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/digit-learning-salesforce-update/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/digit-learning-salesforce-update/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/digit-learning-salesforce-update/screenshot-4.webp"}]'::jsonb WHERE slug = 'digit-learning-salesforce-update';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/fasha-apex-backend-optimization/cover.webp"},{"alt":"Screenshot 1","src":"/projects/fasha-apex-backend-optimization/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/fasha-apex-backend-optimization/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/fasha-apex-backend-optimization/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/fasha-apex-backend-optimization/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/fasha-apex-backend-optimization/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/fasha-apex-backend-optimization/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/fasha-apex-backend-optimization/screenshot-7.webp"},{"alt":"Screenshot 8","src":"/projects/fasha-apex-backend-optimization/screenshot-8.webp"},{"alt":"Screenshot 9","src":"/projects/fasha-apex-backend-optimization/screenshot-9.webp"},{"alt":"Screenshot 10","src":"/projects/fasha-apex-backend-optimization/screenshot-10.webp"},{"alt":"Screenshot 11","src":"/projects/fasha-apex-backend-optimization/screenshot-11.webp"},{"alt":"Screenshot 12","src":"/projects/fasha-apex-backend-optimization/screenshot-12.webp"},{"alt":"Screenshot 13","src":"/projects/fasha-apex-backend-optimization/screenshot-13.webp"},{"alt":"Screenshot 14","src":"/projects/fasha-apex-backend-optimization/screenshot-14.webp"},{"alt":"Screenshot 15","src":"/projects/fasha-apex-backend-optimization/screenshot-15.webp"},{"alt":"Screenshot 16","src":"/projects/fasha-apex-backend-optimization/screenshot-16.webp"}]'::jsonb WHERE slug = 'fasha-apex-backend-optimization';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/hardware-upgrade-hp-laptop/cover.webp"},{"alt":"Screenshot 1","src":"/projects/hardware-upgrade-hp-laptop/screenshot-1.webp"}]'::jsonb WHERE slug = 'hardware-upgrade-hp-laptop';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/hemebiotech-java-debug/cover.webp"},{"alt":"Screenshot 1","src":"/projects/hemebiotech-java-debug/screenshot-1.webp"}]'::jsonb WHERE slug = 'hemebiotech-java-debug';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/idemconnect-apex-backend/cover.webp"},{"alt":"Screenshot 1","src":"/projects/idemconnect-apex-backend/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/idemconnect-apex-backend/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/idemconnect-apex-backend/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/idemconnect-apex-backend/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/idemconnect-apex-backend/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/idemconnect-apex-backend/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/idemconnect-apex-backend/screenshot-7.webp"},{"alt":"Screenshot 8","src":"/projects/idemconnect-apex-backend/screenshot-8.webp"},{"alt":"Screenshot 9","src":"/projects/idemconnect-apex-backend/screenshot-9.webp"},{"alt":"Screenshot 10","src":"/projects/idemconnect-apex-backend/screenshot-10.webp"},{"alt":"Screenshot 11","src":"/projects/idemconnect-apex-backend/screenshot-11.webp"},{"alt":"Screenshot 12","src":"/projects/idemconnect-apex-backend/screenshot-12.webp"},{"alt":"Screenshot 13","src":"/projects/idemconnect-apex-backend/screenshot-13.webp"},{"alt":"Screenshot 14","src":"/projects/idemconnect-apex-backend/screenshot-14.webp"},{"alt":"Screenshot 15","src":"/projects/idemconnect-apex-backend/screenshot-15.webp"},{"alt":"Screenshot 16","src":"/projects/idemconnect-apex-backend/screenshot-16.webp"}]'::jsonb WHERE slug = 'idemconnect-apex-backend';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-acronis-backup/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-acronis-backup/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/it-ops-acronis-backup/screenshot-2.webp"}]'::jsonb WHERE slug = 'it-ops-acronis-backup';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-disk-backup/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-disk-backup/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/it-ops-disk-backup/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/it-ops-disk-backup/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/it-ops-disk-backup/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/it-ops-disk-backup/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/it-ops-disk-backup/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/it-ops-disk-backup/screenshot-7.webp"},{"alt":"Screenshot 8","src":"/projects/it-ops-disk-backup/screenshot-8.webp"},{"alt":"Screenshot 9","src":"/projects/it-ops-disk-backup/screenshot-9.webp"}]'::jsonb WHERE slug = 'it-ops-disk-backup';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-email-config/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-email-config/screenshot-1.webp"}]'::jsonb WHERE slug = 'it-ops-email-config';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-hardware-procurement/cover.webp"}]'::jsonb WHERE slug = 'it-ops-hardware-procurement';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-incident-management/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-incident-management/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/it-ops-incident-management/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/it-ops-incident-management/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/it-ops-incident-management/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/it-ops-incident-management/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/it-ops-incident-management/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/it-ops-incident-management/screenshot-7.webp"}]'::jsonb WHERE slug = 'it-ops-incident-management';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-network-security/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-network-security/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/it-ops-network-security/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/it-ops-network-security/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/it-ops-network-security/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/it-ops-network-security/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/it-ops-network-security/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/it-ops-network-security/screenshot-7.webp"},{"alt":"Screenshot 8","src":"/projects/it-ops-network-security/screenshot-8.webp"},{"alt":"Screenshot 9","src":"/projects/it-ops-network-security/screenshot-9.webp"}]'::jsonb WHERE slug = 'it-ops-network-security';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-rmm-supervision/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-rmm-supervision/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/it-ops-rmm-supervision/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/it-ops-rmm-supervision/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/it-ops-rmm-supervision/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/it-ops-rmm-supervision/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/it-ops-rmm-supervision/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/it-ops-rmm-supervision/screenshot-7.webp"}]'::jsonb WHERE slug = 'it-ops-rmm-supervision';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-roaming-profiles/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-roaming-profiles/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/it-ops-roaming-profiles/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/it-ops-roaming-profiles/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/it-ops-roaming-profiles/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/it-ops-roaming-profiles/screenshot-5.webp"}]'::jsonb WHERE slug = 'it-ops-roaming-profiles';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-virtualization-lab/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-virtualization-lab/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/it-ops-virtualization-lab/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/it-ops-virtualization-lab/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/it-ops-virtualization-lab/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/it-ops-virtualization-lab/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/it-ops-virtualization-lab/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/it-ops-virtualization-lab/screenshot-7.webp"},{"alt":"Screenshot 8","src":"/projects/it-ops-virtualization-lab/screenshot-8.webp"},{"alt":"Screenshot 9","src":"/projects/it-ops-virtualization-lab/screenshot-9.webp"},{"alt":"Screenshot 10","src":"/projects/it-ops-virtualization-lab/screenshot-10.webp"},{"alt":"Screenshot 11","src":"/projects/it-ops-virtualization-lab/screenshot-11.webp"},{"alt":"Screenshot 12","src":"/projects/it-ops-virtualization-lab/screenshot-12.webp"},{"alt":"Screenshot 13","src":"/projects/it-ops-virtualization-lab/screenshot-13.webp"},{"alt":"Screenshot 14","src":"/projects/it-ops-virtualization-lab/screenshot-14.webp"},{"alt":"Screenshot 15","src":"/projects/it-ops-virtualization-lab/screenshot-15.webp"},{"alt":"Screenshot 16","src":"/projects/it-ops-virtualization-lab/screenshot-16.webp"},{"alt":"Screenshot 17","src":"/projects/it-ops-virtualization-lab/screenshot-17.webp"}]'::jsonb WHERE slug = 'it-ops-virtualization-lab';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-wifi-config/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-wifi-config/screenshot-1.webp"}]'::jsonb WHERE slug = 'it-ops-wifi-config';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/it-ops-workstation-setup/cover.webp"},{"alt":"Screenshot 1","src":"/projects/it-ops-workstation-setup/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/it-ops-workstation-setup/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/it-ops-workstation-setup/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/it-ops-workstation-setup/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/it-ops-workstation-setup/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/it-ops-workstation-setup/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/it-ops-workstation-setup/screenshot-7.webp"}]'::jsonb WHERE slug = 'it-ops-workstation-setup';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/legarant-axg-salesforce-deployment/cover.webp"},{"alt":"Screenshot 1","src":"/projects/legarant-axg-salesforce-deployment/screenshot-1.webp"},{"alt":"Screenshot 2","src":"/projects/legarant-axg-salesforce-deployment/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/legarant-axg-salesforce-deployment/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/legarant-axg-salesforce-deployment/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/legarant-axg-salesforce-deployment/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/legarant-axg-salesforce-deployment/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/legarant-axg-salesforce-deployment/screenshot-7.webp"},{"alt":"Screenshot 8","src":"/projects/legarant-axg-salesforce-deployment/screenshot-8.webp"},{"alt":"Screenshot 9","src":"/projects/legarant-axg-salesforce-deployment/screenshot-9.webp"}]'::jsonb WHERE slug = 'legarant-axg-salesforce-deployment';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/ltp-apex-backend-prototype/cover.webp"},{"alt":"Screenshot 1","src":"/projects/ltp-apex-backend-prototype/screenshot-1.png"},{"alt":"Screenshot 2","src":"/projects/ltp-apex-backend-prototype/screenshot-2.webp"},{"alt":"Screenshot 3","src":"/projects/ltp-apex-backend-prototype/screenshot-3.webp"},{"alt":"Screenshot 4","src":"/projects/ltp-apex-backend-prototype/screenshot-4.webp"},{"alt":"Screenshot 5","src":"/projects/ltp-apex-backend-prototype/screenshot-5.webp"},{"alt":"Screenshot 6","src":"/projects/ltp-apex-backend-prototype/screenshot-6.webp"},{"alt":"Screenshot 7","src":"/projects/ltp-apex-backend-prototype/screenshot-7.webp"},{"alt":"Screenshot 8","src":"/projects/ltp-apex-backend-prototype/screenshot-8.webp"},{"alt":"Screenshot 9","src":"/projects/ltp-apex-backend-prototype/screenshot-9.webp"},{"alt":"Screenshot 10","src":"/projects/ltp-apex-backend-prototype/screenshot-10.webp"},{"alt":"Screenshot 11","src":"/projects/ltp-apex-backend-prototype/screenshot-11.webp"},{"alt":"Screenshot 12","src":"/projects/ltp-apex-backend-prototype/screenshot-12.webp"},{"alt":"Screenshot 13","src":"/projects/ltp-apex-backend-prototype/screenshot-13.webp"},{"alt":"Screenshot 14","src":"/projects/ltp-apex-backend-prototype/screenshot-14.webp"},{"alt":"Screenshot 15","src":"/projects/ltp-apex-backend-prototype/screenshot-15.webp"},{"alt":"Screenshot 16","src":"/projects/ltp-apex-backend-prototype/screenshot-16.webp"},{"alt":"Screenshot 17","src":"/projects/ltp-apex-backend-prototype/screenshot-17.webp"}]'::jsonb WHERE slug = 'ltp-apex-backend-prototype';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/parkit-java-testing/cover.png"},{"alt":"Screenshot 1","src":"/projects/parkit-java-testing/screenshot-1.png"},{"alt":"Screenshot 2","src":"/projects/parkit-java-testing/screenshot-2.png"},{"alt":"Screenshot 3","src":"/projects/parkit-java-testing/screenshot-3.png"},{"alt":"Screenshot 4","src":"/projects/parkit-java-testing/screenshot-4.png"},{"alt":"Screenshot 5","src":"/projects/parkit-java-testing/screenshot-5.png"},{"alt":"Screenshot 6","src":"/projects/parkit-java-testing/screenshot-6.png"},{"alt":"Screenshot 7","src":"/projects/parkit-java-testing/screenshot-7.png"},{"alt":"Screenshot 8","src":"/projects/parkit-java-testing/screenshot-8.png"},{"alt":"Screenshot 9","src":"/projects/parkit-java-testing/screenshot-9.png"},{"alt":"Screenshot 10","src":"/projects/parkit-java-testing/screenshot-10.png"},{"alt":"Screenshot 11","src":"/projects/parkit-java-testing/screenshot-11.png"},{"alt":"Screenshot 12","src":"/projects/parkit-java-testing/screenshot-12.png"},{"alt":"Screenshot 13","src":"/projects/parkit-java-testing/screenshot-13.png"},{"alt":"Screenshot 14","src":"/projects/parkit-java-testing/screenshot-14.png"},{"alt":"Screenshot 15","src":"/projects/parkit-java-testing/screenshot-15.png"},{"alt":"Screenshot 16","src":"/projects/parkit-java-testing/screenshot-16.png"},{"alt":"Screenshot 17","src":"/projects/parkit-java-testing/screenshot-17.png"}]'::jsonb WHERE slug = 'parkit-java-testing';

UPDATE projects SET gallery = '[{"alt":"Screenshot 1","src":"/projects/pochlib-ui/screenshot-1.png"},{"alt":"Screenshot 2","src":"/projects/pochlib-ui/screenshot-2.png"},{"alt":"Screenshot 3","src":"/projects/pochlib-ui/screenshot-3.png"},{"alt":"Screenshot 4","src":"/projects/pochlib-ui/screenshot-4.png"},{"alt":"Screenshot 5","src":"/projects/pochlib-ui/screenshot-5.png"},{"alt":"Screenshot 6","src":"/projects/pochlib-ui/screenshot-6.png"},{"alt":"Screenshot 7","src":"/projects/pochlib-ui/screenshot-7.png"},{"alt":"Screenshot 8","src":"/projects/pochlib-ui/screenshot-8.png"},{"alt":"Screenshot 9","src":"/projects/pochlib-ui/screenshot-9.png"},{"alt":"Screenshot 10","src":"/projects/pochlib-ui/screenshot-10.png"},{"alt":"Screenshot 11","src":"/projects/pochlib-ui/screenshot-11.png"},{"alt":"Screenshot 12","src":"/projects/pochlib-ui/screenshot-12.png"},{"alt":"Screenshot 13","src":"/projects/pochlib-ui/screenshot-13.png"},{"alt":"Screenshot 14","src":"/projects/pochlib-ui/screenshot-14.png"},{"alt":"Screenshot 15","src":"/projects/pochlib-ui/screenshot-15.png"},{"alt":"Screenshot 16","src":"/projects/pochlib-ui/screenshot-16.png"},{"alt":"Screenshot 17","src":"/projects/pochlib-ui/screenshot-17.png"},{"alt":"Screenshot 18","src":"/projects/pochlib-ui/screenshot-18.png"}]'::jsonb WHERE slug = 'pochlib-ui';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/python-network-scanner/cover.svg"},{"alt":"Screenshot 1","src":"/projects/python-network-scanner/screenshot-1.svg"}]'::jsonb WHERE slug = 'python-network-scanner';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/python-password-checker/cover.svg"},{"alt":"Screenshot 1","src":"/projects/python-password-checker/screenshot-1.svg"}]'::jsonb WHERE slug = 'python-password-checker';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/tours-for-life-salesforce-solution/cover.png"},{"alt":"Screenshot 1","src":"/projects/tours-for-life-salesforce-solution/screenshot-1.png"},{"alt":"Screenshot 2","src":"/projects/tours-for-life-salesforce-solution/screenshot-2.png"},{"alt":"Screenshot 3","src":"/projects/tours-for-life-salesforce-solution/screenshot-3.png"},{"alt":"Screenshot 4","src":"/projects/tours-for-life-salesforce-solution/screenshot-4.png"},{"alt":"Screenshot 5","src":"/projects/tours-for-life-salesforce-solution/screenshot-5.png"},{"alt":"Screenshot 6","src":"/projects/tours-for-life-salesforce-solution/screenshot-6.png"},{"alt":"Screenshot 7","src":"/projects/tours-for-life-salesforce-solution/screenshot-7.png"},{"alt":"Screenshot 8","src":"/projects/tours-for-life-salesforce-solution/screenshot-8.png"},{"alt":"Screenshot 9","src":"/projects/tours-for-life-salesforce-solution/screenshot-9.png"},{"alt":"Screenshot 10","src":"/projects/tours-for-life-salesforce-solution/screenshot-10.png"},{"alt":"Screenshot 11","src":"/projects/tours-for-life-salesforce-solution/screenshot-11.png"},{"alt":"Screenshot 12","src":"/projects/tours-for-life-salesforce-solution/screenshot-12.png"},{"alt":"Screenshot 13","src":"/projects/tours-for-life-salesforce-solution/screenshot-13.png"},{"alt":"Screenshot 14","src":"/projects/tours-for-life-salesforce-solution/screenshot-14.webp"},{"alt":"Screenshot 15","src":"/projects/tours-for-life-salesforce-solution/screenshot-15.webp"}]'::jsonb WHERE slug = 'tours-for-life-salesforce-solution';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/wirebright-visualforce-to-lightning/cover.png"},{"alt":"Screenshot 1","src":"/projects/wirebright-visualforce-to-lightning/screenshot-1.png"},{"alt":"Screenshot 2","src":"/projects/wirebright-visualforce-to-lightning/screenshot-2.png"},{"alt":"Screenshot 3","src":"/projects/wirebright-visualforce-to-lightning/screenshot-3.png"},{"alt":"Screenshot 4","src":"/projects/wirebright-visualforce-to-lightning/screenshot-4.png"},{"alt":"Screenshot 5","src":"/projects/wirebright-visualforce-to-lightning/screenshot-5.png"},{"alt":"Screenshot 6","src":"/projects/wirebright-visualforce-to-lightning/screenshot-6.png"},{"alt":"Screenshot 7","src":"/projects/wirebright-visualforce-to-lightning/screenshot-7.png"},{"alt":"Screenshot 8","src":"/projects/wirebright-visualforce-to-lightning/screenshot-8.png"},{"alt":"Screenshot 9","src":"/projects/wirebright-visualforce-to-lightning/screenshot-9.png"},{"alt":"Screenshot 10","src":"/projects/wirebright-visualforce-to-lightning/screenshot-10.png"},{"alt":"Screenshot 11","src":"/projects/wirebright-visualforce-to-lightning/screenshot-11.png"},{"alt":"Screenshot 12","src":"/projects/wirebright-visualforce-to-lightning/screenshot-12.png"},{"alt":"Screenshot 13","src":"/projects/wirebright-visualforce-to-lightning/screenshot-13.png"},{"alt":"Screenshot 14","src":"/projects/wirebright-visualforce-to-lightning/screenshot-14.png"},{"alt":"Screenshot 15","src":"/projects/wirebright-visualforce-to-lightning/screenshot-15.jpg"},{"alt":"Screenshot 16","src":"/projects/wirebright-visualforce-to-lightning/screenshot-16.png"},{"alt":"Screenshot 17","src":"/projects/wirebright-visualforce-to-lightning/screenshot-17.png"}]'::jsonb WHERE slug = 'wirebright-visualforce-to-lightning';

UPDATE projects SET gallery = '[{"alt":"Cover","src":"/projects/workstation-mass-deployment/cover.png"},{"alt":"Screenshot 1","src":"/projects/workstation-mass-deployment/screenshot-1.png"},{"alt":"Screenshot 2","src":"/projects/workstation-mass-deployment/screenshot-2.png"},{"alt":"Screenshot 3","src":"/projects/workstation-mass-deployment/screenshot-3.png"},{"alt":"Screenshot 4","src":"/projects/workstation-mass-deployment/screenshot-4.png"},{"alt":"Screenshot 5","src":"/projects/workstation-mass-deployment/screenshot-5.png"},{"alt":"Screenshot 6","src":"/projects/workstation-mass-deployment/screenshot-6.png"},{"alt":"Screenshot 7","src":"/projects/workstation-mass-deployment/screenshot-7.png"},{"alt":"Screenshot 8","src":"/projects/workstation-mass-deployment/screenshot-8.png"},{"alt":"Screenshot 9","src":"/projects/workstation-mass-deployment/screenshot-9.png"},{"alt":"Screenshot 10","src":"/projects/workstation-mass-deployment/screenshot-10.png"},{"alt":"Screenshot 11","src":"/projects/workstation-mass-deployment/screenshot-11.png"},{"alt":"Screenshot 12","src":"/projects/workstation-mass-deployment/screenshot-12.png"},{"alt":"Screenshot 13","src":"/projects/workstation-mass-deployment/screenshot-13.png"},{"alt":"Screenshot 14","src":"/projects/workstation-mass-deployment/screenshot-14.png"},{"alt":"Screenshot 15","src":"/projects/workstation-mass-deployment/screenshot-15.jpg"},{"alt":"Screenshot 16","src":"/projects/workstation-mass-deployment/screenshot-16.jpg"},{"alt":"Screenshot 17","src":"/projects/workstation-mass-deployment/screenshot-17.jpg"}]'::jsonb WHERE slug = 'workstation-mass-deployment';
